#pragma once

#include "ResultOr.hpp"
#include "CoordinateSystem.h"
#include "Csw.hpp"
#include "Shape.hpp"
#include "Mesh.hpp"
#include "Triangulation.h"
#include "GraphId.h"
#include "AssemblyGraph.h"
#include "AssemblySettings.hpp"
#include "AssemblyGraphBuilder.h"
#include "AssemblyBuilder.h"
#include "StepData.h"
#include "StepReader.h"
#include "StepWriter.h"
#include "Pipeliner.h"